baseURL = 'http://terreorange.com/'
languageCode = 'fr-fr'
theme = 'terreorange'
title = "terreorange"
description = "Expériences : dessins, peintures, photographies, animations, histoires et autres textes"
