baseURL = 'http://hugo.terreorange.fr/'
languageCode = 'fr-FR'
theme = 'terreorange-v2'
title = "terreorange"
paginate = 12

[taxonomies]
	category = 'categories'
	year = 'years'
	
[params]
	description = "Expériences : "

[author]
  name = "Jean-Yves Jourdain"
  email = "jyjourdain@terreorange.com"


[menu]
[[menu.main]]
  identifier = 'contact'
  name = 'Me contacter'
  url = '/contact/'
  weight = 20
[[menu.main]]
  identifier = 'about'
  name = 'À propos'
  url = '/a-propos/'
  weight = 10
  
[permalinks]
  pages = '/:filename/'

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[markup.goldmark.renderer]
unsafe = true
