baseURL = 'http://terreorange.com/'
languageCode = 'fr-FR'
theme = 'terreorange-v2'
title = "terreorange"
paginate = 4

[params]
	description = "Expériences : dessins, peintures, photographies, animations, histoires et autres textes"

[author]
  name = "Jean-Yves Jourdain"
  email = "jyjourdain@terreorange.com"

[menu]
[[menu.main]]
  identifier = 'contact'
  name = 'Me contacter'
  url = '/contact/'
  weight = 10
[[menu.main]]
  identifier = 'about'
  name = 'À propos'
  url = '/a-propos/'
  weight = 20
  
[permalinks]
  pages = '/:filename/'

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false